python inference.py \
--model_name "i2vgenxl" \
--control_types "canny" \
--huggingface_checkpoint_folder "i2vgenxl_canny" \
--eval_input_type "frames" \
--evaluation_input_folder "assets/evaluation/frames" \
--n_sample_frames 16 \
--extract_control_conditions True \
--num_inference_steps 50 \
--control_guidance_end 0.6 \
--height 512 \
--width 512
